version: "3.8"

services:
  sys_manage_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: sys_manage_frontend:latest
    container_name: sys_manage_frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-80}:80"
    networks:
      - keystone_shared

networks:
  keystone_shared:
    external: true
    name: keystone_shared
